<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use App\Models\Car;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds
     */
    public function run(): void
    {
       // Safe delete without violating foreign key constraints
        Car::query()->delete();

        $cars = [
        [
            'make' => 'Mercedes-AMG W13',
            'model' => 'W13',
            'year' => 2022,
            'mileage' => 13000,
            'color' => 'White with Black and Red accents',
            'transmission' => '8-spaced semi-automatic sequential',
            'fuel_type' => 'High-octane E10 (10% ethanol blend)',
            'image' => 'cars/Mercedes-AMG_W13.png',
            'price' => 35400.00,
            'category' => 'Luxury',
        ],
        [
            'make' => 'Toyota Alphard',
            'model' => 'Alphard Executive Lounge',
            'year' => 2022,
            'mileage' => 11200,
            'color' => 'Pearl White',
            'transmission' => 'CVT Automatic',
            'fuel_type' => 'Petrol',
            'image' => 'cars/Toyota_Alphard.png',
            'price' => 10800.00,
            'category' => 'Van',
        ],
        [
            'make' => 'Toyota Harrier',
            'model' => 'Harrier Premium',
            'year' => 2022,
            'mileage' => 28000,
            'color' => 'Jet Black',
            'transmission' => 'Automatic CVT',
            'fuel_type' => 'petrol',
            'image' => 'cars/Toyota_Harrier.png',
            'price' => 12200.00,
            'category' => 'SUV',
        ],
        [
            'make' => 'Toyota Land Cruiser Prado',
            'model' => 'Prado TX-L',
            'year' => 2022,
            'mileage' => 17500,
            'color' => 'Maroon',
            'transmission' => '6-speed automatic',
            'fuel_type' => 'Diesel',
            'image' => 'cars/Toyota_Land_Cruiser_Prado.png',
            'price' => 24000.00,
            'category' => 'SUV',
        ],
        [
            'make' => 'Mazda RX-8',
            'model' => 'RX-8 Type S',
            'year' => 2008,
            'mileage' => 7000,
            'color' => 'Crystal White Pearl',
            'transmission' => '6-speed manual',
            'fuel_type' => 'Petrol',
            'image' => 'cars/Mazda_RX-8.png',
            'price' => 16000.00,
            'category' => 'Sports',
        ],
        [
            'make' => 'Toyota GT86',
            'model' => 'GT86 Base',
            'year' => 2015,
            'mileage' => 32000,
            'color' => 'Pearl White',
            'transmission' => '6-speed manual',
            'fuel_type' => 'petrol',
            'image' => 'cars/Toyota_GT86.png',
            'price' => 21500.00,
            'category' => 'Sports',
        ],
        [
            'make' => 'Audi A7 Sportback',
            'model' => 'A7 55 TFSI Quattro S-Line',
            'year' => 2021,
            'mileage' => 4000,
            'color' => 'Mythos Black Metallic',
            'transmission' => '7-speed S tronic automatic',
            'fuel_type' => 'petrol',
            'image' => 'cars/Audi_A7_Sportback.png',
            'price' => 30000.00,
            'category' => 'Luxury',
        ],
        [
            'make' => 'Toyota Mark X',
            'model' => 'Mark X 250G',
            'year' => 2012,
            'mileage' => 25000,
            'color' => 'Super White',
            'transmission' => '6-speed automatic',
            'fuel_type' => 'petrol',
            'image' => 'cars/Toyota_Mark_X.png',
            'price' => 10500.00,
            'category' => 'Sedan',
        ],
        [
            'make' => 'Audi RS7',
            'model' => 'RS7 Sportback performance',
            'year' => 2022,
            'mileage' => 3000,
            'color' => 'Glacier White Metallic',
            'transmission' => '8-speed Tiptronic automatic',
            'fuel_type' => 'petrol',
            'image' => 'cars/Audi_RS7.png',
            'price' => 26000.00,
            'category' => 'Luxury',
        ],
        [
            'make' => 'Range Rover',
            'model' => 'Range Rover Sport HSE Dynamic',
            'year' => 2022,
            'mileage' => 2300,
            'color' => 'Santorini Black',
            'transmission' => '8-speed automatic',
            'fuel_type' => 'Diesel',
            'image' => 'cars/Range_Rover.png',
            'price' => 48500.00,
            'category' => 'SUV',
        ],
        [
            'make' => 'Toyota Land Cruiser 100',
            'model' => 'Land Cruiser VX',
            'year' => 2002,
            'mileage' => 38000,
            'color' => 'Silver Metallic',
            'transmission' => '5-speed automatic',
            'fuel_type' => 'Diesel',
            'image' => 'cars/Toyota_Land_Cruiser_100.png',
            'price' => 18000.00,
            'category' => 'SUV',
        ],
        [
            'make' => 'Mercedes-AMG GT 63 S',
            'model' => 'GT 63 S 4-Door Coupe',
            'year' => 2022,
            'mileage' => 1200,
            'color' => 'Obsidian Black Metallic',
            'transmission' => '9-speed AMG speedshift MCT',
            'fuel_type' => 'petrol',
            'image' => 'cars/Mercedes-AMG_GT_63_S.png',
            'price' => 50000.00,
            'category' => 'Luxury',
        ],
        [
            'make' => 'Mercedes-AMG GT Coupe',
            'model' => 'GT Coupe V8 Biturbo',
            'year' => 2020,
            'mileage' => 1600,
            'color' => 'Sunbeam Yellow',
            'transmission' => '7-speed AMG Speedshift DCT',
            'fuel_type' => 'petrol',
            'image' => 'cars/Mercedes-AMG_GT_Coupe.png',
            'price' => 62000.00,
            'category' => 'Luxury',
        ],
        [
            'make' => 'Ford Mustang GT',
            'model' => 'Mustang GT Premium Fastback',
            'year' => 2019,
            'mileage' => 10000,
            'color' => 'Need for Green with Black Racing Stripes',
            'transmission' => '6-speed manual',
            'fuel_type' => 'petrol',
            'image' => 'cars/Ford_Mustang_GT.png',
            'price' => 46500.00,
            'category' => 'Sports',
        ],
        [
            'make' => 'Lamborghini Huracán EVO',
            'model' => 'Huracán EVO Coupe',
            'year' => 2020,
            'mileage' => 2200,
            'color' => 'Arancio Borealis(Orange)',
            'transmission' => '7-speed dual-clutch automatic (LDF)',
            'fuel_type' => 'petrol',
            'image' => 'cars/Lamborghini_Huracán_EVO.png',
            'price' => 80000.00,
            'category' => 'Luxury',
        ],
        [
            'make' => 'Porsche 911 Turbo S',
            'model' => '911 Turbo S Coupe',
            'year' => 2022,
            'mileage' => 1000,
            'color' => 'Jet Black Metallic',
            'transmission' => '8-speed PDK dual-clutch automatic',
            'fuel_type' => 'petrol',
            'image' => 'cars/Porsche_911_Turbo_S.png',
            'price' => 68000.00,
            'category' => 'Luxury',
        ],
        [
            'make' => 'Chevrolet Camaro',
            'model' => 'Camaro SS Coupe',
            'year' => 2020,
            'mileage' => 17000,
            'color' => 'Riverside Blue Metallic with Black Accents',
            'transmission' => '6-speed manual',
            'fuel_type' => 'petrol',
            'image' => 'cars/Chevrolet_Camaro.png',
            'price' => 67800.00,
            'category' => 'Sports',
        ],
        [
            'make' => 'Ferrari 488 GTB',
            'model' => '488 GTB Coupe',
            'year' => 2019,
            'mileage' => 1160,
            'color' => 'Rosso Corsa (Red)',
            'transmission' => '7-speed dual-clutch automatic',
            'fuel_type' => 'petrol',
            'image' => 'cars/Ferrari_488_GTB.png',
            'price' => 79700.00,
            'category' => 'Luxury',
        ],
        [
            'make' => 'Subaru WRX',
            'model' => 'WRX Premium',
            'year' => 2021,
            'mileage' => 25000,
            'color' => 'World Rally Blue Pearl',
            'transmission' => '6-speed manual',
            'fuel_type' => 'petrol',
            'image' => 'cars/Subaru_WRX.png',
            'price' => 14800.00,
            'category' => 'Sports',
        ],
        [
            'make' => 'Lexus RX',
            'model' => 'RX 500h F SPORT',
            'year' => 2023,
            'mileage' => 5600,
            'color' => 'Eminet White Pearl',
            'transmission' => '6-speed automatic',
            'fuel_type' => 'Hybrid(Petrol + Electric)',
            'image' => 'cars/Lexus_RX.png',
            'price' => 33000.00,
            'category' => 'SUV',    
        ],
        [
            'make' => 'Cadillac',
            'model' => 'Escalade Platinum',
            'year' => 2023,
            'mileage' => 4000,
            'color' => 'Crystal White Tricoat',
            'transmission' => '10-speed automatic',
            'fuel_type' => 'Petrol',
            'image' => 'cars/cadillac-escalade-winter.png',
            'price' => 92000.00,
            'category' => 'Luxury',
            'is_featured' => true,
        ],
        [
            'make' => 'Audi',
            'model' => 'RS5 Sportback',
            'year' => 2023,
            'mileage' => 3200,
            'color' => 'Mythos Black Metallic',
            'transmission' => '8-speed Tiptronic',
            'fuel_type' => 'Petrol',
            'image' => 'cars/audi-q5-autumn.png',
            'price' => 66000.00,
            'category' => 'Luxury',
            'is_featured' => true,
        ],
        [
            'make' => 'BMW',
            'model' => 'M850i xDrive Coupe',
            'year' => 2023,
            'mileage' => 3500,
            'color' => 'Frozen Bluestone Metallic',
            'transmission' => '8-speed automatic',
            'fuel_type' => 'Petrol',
            'image' => 'cars/bmw-7series-mountain.png',
            'price' => 82000.00,
            'category' => 'Luxury',
            'is_featured' => true,
        ],
        [
            'make' => 'Bentley',
            'model' => 'Continental GT Speed',
            'year' => 2023,
            'mileage' => 2800,
            'color' => 'Sequin Blue',
            'transmission' => '8-speed dual-clutch automatic',
            'fuel_type' => 'Petrol',
            'image' => 'cars/bentley-fot713-street.png',
            'price' => 140000.00,
            'category' => 'Luxury',
            'is_featured' => true,
        ],
        [
            'make' => 'Nissan',
            'model' => 'GT-R Premium',
            'year' => 2023,
            'mileage' => 3000,
            'color' => 'Super Silver QuadCoat',
            'transmission' => '6-speed dual-clutch automatic',
            'fuel_type' => 'Petrol',
            'image' => 'cars/nissan-r33-skyline.png',
            'price' => 56000.00,
            'category' => 'Performance',
            'is_featured' => true,
        ],
        [
            'make' => 'Land Rover',
            'model' => 'Range Rover Autobiography',
            'year' => 2023,
            'mileage' => 3100,
            'color' => 'Santorini Black',
            'transmission' => '8-speed automatic',
            'fuel_type' => 'Diesel',
            'image' => 'cars/range-rover-drive-automobiles.png',
            'price' => 48500.00,
            'category' => 'Luxury',
            'is_featured' => true,
        ],
        [
            'make' => 'Dodge',
            'model' => 'Challenger SRT Hellcat',
            'year' => 2023,
            'mileage' => 2900,
            'color' => 'Go Mango',
            'transmission' => '8-speed automatic',
            'fuel_type' => 'Petrol',
            'image' => 'cars/dodge-amg61-autumn.png',
            'price' => 58000.00,
            'category' => 'Performance',
            'is_featured' => true,
        ],
        [
            'make' => 'Ford',
            'model' => 'Mustang GT',
            'year' => 2023,
            'mileage' => 3100,
            'color' => 'Race Red',
            'transmission' => '10-speed automatic',
            'fuel_type' => 'Petrol',
            'image' => 'cars/ford-explorer-white-field.png',
            'price' => 42000.00,
            'category' => 'Performance',
            'is_featured' => true,
        ],
        ];

        foreach ($cars as $car) {
        $car['vin'] = $this->generateUniqueVin(strtoupper(Str::slug($car['make'], '')) . '_');
        Car::create($car);
    }
    }

    private function generateUniqueVin($prefix): string
    {
        do {
            $vin = $prefix . Str::upper(Str::random(10));
        } while (Car::where('vin', $vin)->exists());

        return $vin;
    }
}